server:
  port: 8080

logging:
  level:
    org.springframework.cloud.gateway: DEBUG
    org.springframework.cloud.loadbalancer: DEBUG
    org.springframework.web.reactive: DEBUG

spring:
  application:
    name: api-gateway

  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true

      globalcors:
        cors-configurations:
          "[/**]":
            allowedOrigins:
              - "http://localhost:3001"
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
              - OPTIONS
            allowedHeaders: "*"
            allowCredentials: true

      routes:
        # LOGIN microservice (no protegido)
        - id: login-service
          uri: lb://login-service
          predicates:
            - Host=obama.localhost
            - Path=/login/**
          filters:
            - StripPrefix=1

        # CUSTOMER microservice (protegido con JWT)
        - id: customer-service
          uri: lb://customer-service
          predicates:
            - Host=obama.localhost
            - Path=/customers/**
          filters:
            - StripPrefix=1
            - name: JwtAuthenticationFilter

eureka:
  client:
    service-url:
      defaultZone: http://eureka-server:8761/eureka/
