server:
  port: 8080

spring:
  application:
    name: api-gateway

  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true

      routes:
        - id: login-service
          uri: lb://login-service
          predicates:
            - Path=/login/**
          filters:
            - StripPrefix=1 # elimina "/login" y pasa lo demás al servicio

eureka:
  client:
    service-url:
      defaultZone: http://${EUREKA_HOST:localhost}:${EUREKA_PORT:8761}/eureka/
